import { z } from "zod";

// 11 dozwolonych wartości statusu — musi być zgodne z constraint pipeline_status_check
// w supabase/migrations/0001_pipeline_schema.sql.
export const PIPELINE_STATUSES = [
  "Nowy lead",
  "Kwalifikacja",
  "Discovery umówione",
  "Niekwalifikowany",
  "Nieaktywny (follow up)",
  "Finalizacja",
  "Kickoff",
  "Wdrożenie",
  "Retainer",
  "Upsell",
  "Zakończona współpraca",
] as const;

// Pola biznesowe tabeli public.pipeline (bez id/notion_page_id/created_at/updated_at).
// Nazwy 1:1 z nazwami kolumn w bazie — współdzielone przez POST (tworzenie) i PATCH
// (aktualizacja częściowa) w app/api/pipeline/.
const pipelineFieldsSchema = z.object({
  firma: z.string().min(1).optional(),
  telefon: z.string().nullable().optional(),
  utracony: z.boolean().optional(),
  data_oferty: z.string().nullable().optional(),
  srednia_wartosc_faktury_pln: z.number().nullable().optional(),
  historia_zgloszen_retainer: z.string().nullable().optional(),
  decydent: z.boolean().optional(),
  uwagi_agenta_1: z.string().nullable().optional(),
  nastepny_krok: z.string().nullable().optional(),
  spedytorzy: z.number().nullable().optional(),
  re_engagement: z.string().nullable().optional(),
  roi_dopowiedzenie: z.string().nullable().optional(),
  cel_efektywnosci_procent: z.number().nullable().optional(),
  dostepy_zebrane: z.string().nullable().optional(),
  wynik_discovery: z.string().nullable().optional(),
  retainer_pln_mc: z.number().nullable().optional(),
  podejscie_tms: z.string().nullable().optional(),
  przewidywane_obiekcje: z.string().nullable().optional(),
  faktury_po_terminie_mc: z.number().nullable().optional(),
  personalizacja_prezentacji: z.string().nullable().optional(),
  ryzyka_rozmowy: z.string().nullable().optional(),
  konkurencja_wspomniana: z.string().nullable().optional(),
  data_discovery: z.string().nullable().optional(),
  warunki_umowy_dni_dostepow: z.number().nullable().optional(),
  warunki_umowy_uwagi: z.string().nullable().optional(),
  hipoteza_bol_glowny: z.string().nullable().optional(),
  powod_utraty: z.string().nullable().optional(),
  koszt_problemu_pln_mc: z.number().nullable().optional(),
  obiekcje: z.string().nullable().optional(),
  cytaty_klienta: z.string().nullable().optional(),
  email: z.string().nullable().optional(),
  czas_bazowy_potwierdzony_h_mc: z.number().nullable().optional(),
  tms: z.string().nullable().optional(),
  protokol_odbioru_podpisany: z.boolean().optional(),
  typ_follow_up: z.string().nullable().optional(),
  kickoff_odbyty: z.boolean().optional(),
  liczba_prob_kontaktu: z.number().nullable().optional(),
  kontakt: z.string().nullable().optional(),
  nip: z.string().nullable().optional(),
  pilnosc: z.string().nullable().optional(),
  maile_ze_zleceniami_dzien: z.number().nullable().optional(),
  uwagi_agenta_2: z.string().nullable().optional(),
  ostatni_kontakt_retainer: z.string().nullable().optional(),
  kalkulator_dane: z.string().nullable().optional(),
  uwagi_agenta_4: z.string().nullable().optional(),
  data_kickoff: z.string().nullable().optional(),
  godziny_wpisywania_spedytor: z.number().nullable().optional(),
  data_nastepnego_kroku: z.string().nullable().optional(),
  status: z.enum(PIPELINE_STATUSES).nullable().optional(),
  pomysl_na_funkcje: z.string().nullable().optional(),
  flota: z.number().nullable().optional(),
  data_zamkniecia: z.string().nullable().optional(),
  ocena_icp: z.string().nullable().optional(),
  koszt_roczny_pln_rok: z.number().nullable().optional(),
  zrodlo: z.string().nullable().optional(),
  tabela_modulow_kickoff: z.string().nullable().optional(),
  system_transformacji_3_kroki: z.string().nullable().optional(),
  tabela_modulow_weryfikacja: z.string().nullable().optional(),
  wszystkie_transkrypty: z.string().nullable().optional(),
  cena_wdrozenia: z.number().nullable().optional(),
  zdanie_roznicujace: z.string().nullable().optional(),
  poprzednie_proby: z.string().nullable().optional(),
  data_protokolu_odbioru: z.string().nullable().optional(),
  bol_glowny: z.string().nullable().optional(),
  powod_rezygnacji: z.string().nullable().optional(),
  notatki: z.string().nullable().optional(),
  data_pierwszego_kontaktu: z.string().nullable().optional(),
  gotowosc_zakupowa: z.string().nullable().optional(),
  poza_zakresem_ustalenia: z.string().nullable().optional(),
  moduly_wdrazane: z.array(z.string()).nullable().optional(),
  data_potwierdzenia_dostepow: z.string().nullable().optional(),
  pitch_recipe: z.string().nullable().optional(),
  tabela_modulow_przedkontraktowa: z.string().nullable().optional(),
});

export const pipelineCreateSchema = pipelineFieldsSchema.extend({
  firma: z.string().min(1, "Pole 'firma' jest wymagane"),
});

export const pipelinePatchSchema = pipelineFieldsSchema.partial();
